name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build at rust/
      run: |
        pushd rust/
        cargo test --verbose
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        wasm-pack build
        ls -l pkg/  # For debug
        popd

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Build at javascript/
      run: |
        pushd javascript/
        npm install
        npm run build
        ls -l ../docs/ # For debug
        popd

    - name: Push to gh-pages branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git branch -D gh-pages
        git branch -c gh-pages
        git add docs/* --force
        git commit --message "Deploy docs/*"

        git branch
        git log -1

        # git push --force origin gh-pages