name: test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: npm install, build, and test
        run: |
          npm install
          npm run check:format
          npm test
        env:
          CI: true
