name: test-rs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: |
        cd reversi-wasm

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
